# Generated by Django 5.2.8 on 2025-11-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(verbose_name='Название издательства'),
        ),
    ]
