# Generated by Django 5.2.6 on 2026-01-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.IntegerField(primary_key=True, serialize=False, verbose_name='Article')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2, verbose_name='Size')),
                ('art_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='just_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
