# Generated by Django 5.2.6 on 2026-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_app', '0002_product_size_delete_item_delete_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='art_product',
        ),
        migrations.AddField(
            model_name='size',
            name='art_product',
            field=models.ManyToManyField(to='just_app.product', verbose_name='Product'),
        ),
    ]
